name: Deploy to Server

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Accessing SSH from the Server, Install Dependencies and Build the project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo su
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git checkout main
            git pull origin main
            ./deploy
            echo Finished!